version: '3'
services:
    api:
        container_name: "api"
        build:
            context: ./api
            dockerfile: Dockerfile
        command: ["/usr/wait-for-it.sh", "db:5433", "--", "npm", "run", "dev"]
        ports:
            - "5000:5000"
        env_file:
            - .env
        volumes:
            - ./api:/api-src
            - /api-src/node_modules
        depends_on:
            - db
    db:
        container_name: "db"
        build: ./db
        ports: 
            - "5433:5432"
        env_file:
            - .env
        volumes:
            - "./db/postgres-data:/var/lib/postgresql/data"
        expose:
            - "5432"